#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: scripts/workon.sh /absolute/path/to/project-repo"
  exit 1
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
proj_path="$(realpath "$1")"
[[ -d "$proj_path" ]] || {
  echo "Not a directory: $proj_path"
  exit 1
}

proj_name="$(basename "$proj_path")"
override_dir="$repo_root/.local"
override_file="$override_dir/override.yml"
mkdir -p "$override_dir"

# Optional env_file block (use real newlines)
env_file_block=""
if [[ -f "$proj_path/.env" ]]; then
  env_file_block=$'    env_file:\n      - "'"$proj_path"'/.env"'
fi

# IMPORTANT: We replicate your base volumes here to avoid replacing them,
# then append the project mount at the end.
cat >"$override_file" <<EOF
# Generated by scripts/workon.sh -- DO NOT COMMIT
services:
  ros:
    volumes:
      - ./:/work
      - devhome:/home/ubuntu
      - /run/user/\${USER_ID}:/run/user/\${USER_ID}
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.config/nvim:/home/ubuntu/.config/nvim:ro
      - ~/.local/share/nvim:/home/ubuntu/.local/share/nvim
      - ~/.cache/nvim:/home/ubuntu/.cache/nvim
      - ~/.local/state:/home/ubuntu/.local/state
      - ~/.cache/pip:/home/ubuntu/.cache/pip
      - ~/.cache/clangd:/home/ubuntu/.cache/clangd
      - ~/.cache/colcon:/home/ubuntu/.cache/colcon
      - ~/.config/lazygit:/home/ubuntu/.config/lazygit
      - ~/.zshrc:/home/ubuntu/.zshrc
      - ~/.zprofile:/home/ubuntu/.zprofile
      - ~/.zshenv:/home/ubuntu/.zshenv
      - ~/.oh-my-zsh:/home/ubuntu/.oh-my-zsh
      - ~/.p10k.zsh:/home/ubuntu/.p10k.zsh
      - ~/.ssh:/home/ubuntu/.ssh:ro
      - ~/.gitconfig:/home/ubuntu/.gitconfig:ro
      - "$proj_path:/work/$proj_name"
    working_dir: /work/$proj_name
$(printf "%s" "$env_file_block")
EOF

cd "$repo_root"
# docker compose -f docker-compose.yml -f "$override_file" up -d --force-recreate
# docker compose -f docker-compose.yml -f "$override_file" exec -w "/work/$proj_name" ros bash -lc 'source /opt/ros/kilted/setup.zsh; printf "\n✅ Mounted at: %s\n" "$PWD"; ls -a; exec zsh || exec bash'
docker compose -f docker-compose.yml -f "$override_file" run --rm -w "/work/$proj_name" ros zsh -lc 'source /opt/ros/kilted/setup.zsh; printf "\n✅ Mounted at: %s\n" "$PWD"; ls -a; zsh'
